name: Check signatures format
on:
  pull_request:
    branches:
      - main
    paths:
      - _data/signed/*
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    #runs-on:
    #  group: Default
    #  labels: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: whoami
        run: whoami
      - name: Check signatures format
        run: python3 check-signatures-format.py
